config/routes.rb
Rails.application.routes.draw do
  resources :kits

  resources :items

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :organizations

  resources :homepage

  root 'homepage#index'
  get  'choose'   => 'homepage#choose'
  get  'drop_off' => 'homepage#drop_off'
  get  'donate'   => 'homepage#donate'
  get  'share'    => 'homepage#share'
  post 'share'    => 'homepage#share'
  get  'team'     => 'homepage#team'
  get  'others'   => 'homepage#others'
  get  'hope'     => 'homepage#hope'
  get  'end'      => 'homepage#end'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :kit
end

app/models/kit.rb
class Kit < ActiveRecord::Base
  belongs_to :organization
  has_many :items
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  acts_as_nested_set
  has_many :kits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  before_action :set_org

  def index
    # Mobilize the Charlotte-Mechklenburg community to end chronic homelessness
  end

  def donate
    @total_cost = @org.kits.first.items.map(&:price).sum
  end

  def others
    @organizations = Organization.all
  end

  def share
  end

  def set_org
    if params[:action].eql?('index')
      if params.has_key?(:org)
        @org = Organization.find_by_name(params[:org])
      else
        @org = Organization.all.sample
      end
      cookies['org_id'] = @org.id
    else
      @org = Organization.find(cookies['org_id'])
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < InheritedResources::Base

  private

    def item_params
      params.require(:item).permit(:kit_id, :name, :price)
    end
end

app/controllers/kits_controller.rb
class KitsController < InheritedResources::Base

  private

    def kit_params
      params.require(:kit).permit(:organization_id, :name, :description, :total)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < InheritedResources::Base

  private

    def organization_params
      params.require(:organization).permit(:name, :parent_id, :lft, :rgt)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper

    def menu_active(menu_name)
        menu_name.eql?(params['action']) ? 'active' : ''
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/kits_helper.rb
module KitsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/homepage/choose.html.erb
      <div class="row">
        <div class="jumbotron set-height">
          <div class="container">
            <div class="row">
              <div class="box col-md-6">
                <img class="img-responsive" src="http://res.cloudinary.com/dxhabwozn/image/upload/v1430789378/icons/OpenBox.png">
              </div>
              <div class="valign col-md-6">
                <div class="heading-box">
                  <div class="choose">
                    Choose
                  </div>
                  <div class="your_path">
                    Your Path
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <hr />

        <div class="container">
          <div class="row">
            
            <a href="donate">
              <div class="col-md-6">
                <div class="donate_money"></div>
                <div class="donatetodayblack">Donate <span>Money</span> Today</div>
              </div>
            </a>
            
            <a href="drop_off">
              <div class="col-md-6">
                <div class="donate_kit"></div>
                <div class="donatetodayblack">Donate a <span>Physical Kit</span></div>
              </div>
            </a>

          </div>
        </div>
      </div>

app/views/homepage/donate.html.erb
      <div class="row">
        <div class="jumbotron set-height">
          <div class="container">
            <div class="row">
              <div class=" col-md-6">
                <img class="img-responsive" src="http://res.cloudinary.com/dxhabwozn/image/upload/v1430789378/icons/OpenBox.png">
              </div>
              <div class="valign_donate col-md-6">
                <div class="heading-box-donate">
                  Every donation is a small step towards success         
                </div>
                <p id="donate_amount">$1</p>
                <input id="slider1" type="range" value="0" min="1" max="<%= @total_cost.to_f.to_s %>" step="1" onmousemove="updateDonationDisplay(this.value);" onchange="updateDonationDisplay(this.value); highlightItems(this.value);"  />
                <%= form_tag '/share', id: 'donateForm' do %>
                <div class="donatetodayblack">Donate this <span>Amount</span></div>
                <input id="hidden_amount" type="hidden" name="amount" value="">
                <% end %>
              </div>
            </div>
          </div>
        </div>


        <script type="text/javascript">
        function updateDonationDisplay(value){
          $('#donate_amount')[0].innerHTML = '$' + value
          $('#hidden_amount')[0].value = value;
        }
        function highlightItems(money){
          $('.items').each(function(index, value){
            tmp_index = value.id.split('-')[0];
            tmp_value = value.id.split('-')[1];
            money = parseInt(money);
            tmp_value = parseInt(tmp_value);
            if(tmp_value <= money){
              $(value).addClass('items-paid').animate({opacity: "1"}, 200);
              money = money - tmp_value;
            }else{
              $(value).removeClass('items-paid').animate({opacity: ".33"}, 200);
            }

          })
        }
        </script>

<hr />
        <div class="container" style="width: 100%;">
          <div class="row">
            <div class="col-md-12">
              <div class="row">
                <% @items = @org.kits.sample.items %>
                <% @items.each_with_index do |item, index| %>
                <div class="items col-md-3 col-lg-2" id="<%= index %>-<%= item.price %>">
                  <img class="donate_image" src="<%= item.image_url %>">
                  <p class="itemname"><%= item.name %><br><%= number_to_currency(item.price) %></p>

                </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>



        <script src="https://checkout.stripe.com/checkout.js"></script>

        <!-- <button id="customButton">Purchase</button> -->

      <script>
        var handler = StripeCheckout.configure({
          key: 'pk_test_6pRNASCoBOKtIshFeQd4XMUh',
          image: 'http://placehold.it/100x100/3a3a3c&text=KS',
          token: function(token) {
            document.getElementById('donateForm').submit();
          }
        });

        $('.donatetodayblack').on('click', function(e) {
          // Open Checkout with further options
          var amount = document.getElementById('slider1').value;
          handler.open({
            name: '<%= @org.name %>',
            description: '',
            amount: amount + '00'
          });
          e.preventDefault();
        });

        // Close Checkout on page navigation
        $(window).on('popstate', function() {
          handler.close();
        });
      </script>

app/views/homepage/drop_off.html.erb
  <div class="row">
    <div class="jumbotron set-height">
      <div class="container">
        <div class="row">
          <div class="box col-md-6">
            <img src="http://res.cloudinary.com/dxhabwozn/image/upload/v1431396645/Handtruck-boxes_kw0pdk.png">
          </div>
          <div class="valign col-md-6">
            <div class="heading-box">
              <div class="choose">
                directions
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <hr />

    <div class="container">
      <div class="row">

        <div class="col-md-4">
          <h2 class="center bigger">WHO</h2>
          <p class="center plus_one">
            <%= @org.kits.first.who %>
          </p>
        </div>

        <div class="col-md-4">
          <h2 class="center bigger">WHEN</h2>
          <p class="center plus_one">
            <%= @org.kits.first.when %>
          </p>
        </div>

        <div class="col-md-4">
          <h2 class="center bigger">WHERE</h2>
          <p class="center plus_one">
            <%= @org.kits.first.where %>
          </p>
        </div>

      </div>
    </div>

    <div class="container" style="width: 100%;">
      <div class="row">
        <div class="col-md-12">
          <h2 class="center bigger">WHAT</h2>
          <div class="row">
            <% @items = @org.kits.first.items %>
            <% @items.each do |item| %>
            <div class="col-md-3 col-lg-2">
              <img class="drop_off_image" src="<%= item.image_url %>">
              <p class="itemname"><%= item.name %><br></p>
              <br />
            </div>
            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>

app/views/homepage/end.html.erb
  <div class="row">
    <div class="jumbotron set-height">

      <h2>You awesome.  Not like hannah, rebecca or simone. #broken</h2>

    </div>
  </div>

app/views/homepage/hope.html.erb
      <div class="row">
        <div class="topsection set-height ourhope description">
          <div class="shadow">
            <p>Kit Start is a tool to "donate today" those often overlooked, but necessary, items to those in need. A small kit makes for a big step towards success.</p>
          </div>  
        </div>      
        
        <div class="container">
          <div class="row">
            <div class="col-sm-4">
              <!-- <img class="img-square" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140"> -->
              <h2>Less Mass Market</h2>
              <p>Kit Start provbides a website dedicated to one organizxation and cause. You don't get overwhlemed by all the options.</p>
            </div><!-- /.col-sm-4 -->
            <div class="col-sm-4">
              <!-- <img class="img-square" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140"> -->
              <h2>Donate or Drop off</h2>
              <p>You can conate a monetary amount based on actual items with your credit card. Or drop off a physical kit with clear directions.</p>
            </div><!-- /.col-sm-4 -->
            <div class="col-sm-4">
              <!-- <img class="img-square" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140"> -->
              <h2>Spread the Word</h2>
              <p>You should feel awesome when you donate. Share your good work and encourage others to donate too! Spread the good cause.</p>
            </div><!-- /.col-sm-4 -->    
          </div>
        </div>
      </div>

app/views/homepage/index.html.erb
      <div class="row">
        <div class="topsection call_to_action set-height">
          <div class="mainshadow">
            <div class="action"><%= raw @org.call_to_action %></div>
            <a href="choose"><div class="donatetoday">Donate<br/><span>Today</span></div></a>
          </div>
        </div>



        <div class="topsection description set-height">
          <div class="shadow">
            <div class="explaination">
              <%= @org.kits.first.description %>
            </div>
          </div>
        </div>



        <div class="row">
          <div class="col-sm-6 left leftthird">
            <p>
              <img class="img-responsive" src="http://res.cloudinary.com/dxhabwozn/image/upload/v1429962053/kitstart-favicon_pxvhxj.png">
            </p>
            <div class="lowerthirdtext">
              <h3>kit | start</h3>
              <p>
                Kit Start is a tool to "donate today" those often overlooked, but necessary, items to those in need. A small kit makes for a big step towards success.
              </p>
            </div>
            <a href="hope"><div class="donatetoday">Our<br/><span>Hope</span></div></a>
          </div>

          <div class="col-sm-6 lowerthird">
            <p>
              <img class="img-square" src="<%= @org.logo_url %>" alt="Org Logo" width="240" height="140"> 
            </p>
            <div class="lowerthirdtext">
              <h3><%= @org.name %></h3>
              <p>
                <%= @org.lower_third %>
              </p>
            </div>
            <a href="choose"><div class="donatetoday hvr-float">Donate<br/><span>Today</span></div></a>
          </div>
        </div>

      </div>

      <style type="text/css">
      .call_to_action {
        background: url('<%= @org.homepage_bg_image_url %>') no-repeat center;
        background-size: cover;

      }
      .description {
        background: url('<%= @org.description_image_url %>') no-repeat center;
        background-size: cover;
      }
      </style>

app/views/homepage/others.html.erb
      <div class="row">    
        <div class="topsection set-height others description">
          <div class="shadow">
            <p>See some other organizations participating in Kit Start.</p>
          </div>
        </div>

        <div class="container">

          <% @organizations.in_groups_of(2) do |group| %>
          <div class="row">
            <% group.each do |org| %>
            <div class="col-sm-6">
              <a href="/?org=<%= org.name %>">
                <img class="img-square" src="<%= org.logo_url %>" alt="Org Logo" width="240" height="140">
                <h2><%= org.name %></h2>
              </a>
              <p><%= org.lower_third %></p>
            </div><!-- /.col-sm-6 -->
            <% end %>
          </div>
          <% end %>

app/views/homepage/pay.html.erb
      <div class="row">
        <div class="jumbotron set-height">
          <div class="row">
            <div class="box col-md-5">
            </div>
            <div class="col-md-7">
              <div class="border-box">
                <div class="choose">
                  Enter
                </div>
                <div class="your_path">
                  Payment info
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="container">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">

             




             <!-- <div class="row greenpay">Stripe wicked easy option</div> -->
             <form action="" method="POST" class="stripe">
               <script
               src="https://checkout.stripe.com/checkout.js" class="stripe-button"
               data-key="pk_test_6pRNASCoBOKtIshFeQd4XMUh"
               data-amount="2000"
               data-name="Demo Site"
               data-description="2 widgets ($20.00)"
               data-image="http://placehold.it/100x100/008F89&text=KS"
               data-panel-label="Donate Today"
               data-label="Donate"
               data-allow-remember-me="false">
               </script>
             </form>

             

           </div>
         </div>
       </div>






     </div>

app/views/homepage/share.html.erb
      <div class="row">
        <div class="jumbotron set-height">
          <div class="container">
            <div class="row">
              <div class="box col-md-6">
                <img class="img-responsive" src="http://res.cloudinary.com/dxhabwozn/image/upload/v1430789378/icons/OpenBox.png">
              </div>
              <div class="valign_donate col-md-6">
                <div class="heading-box">
                  <div class="choose">
                    You're
                  </div>
                  <div class="your_path">
                    Awesome!
                  </div>
                </div>
                <div class="path_desc">
                  <p style="font-size: 27px;">Thank you for your donation of $<%= params['amount'] %></p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <hr/>

        <div class="row socialshare">
          <div class="col-md-6 col-md-offset-3">

            <div class="heading-box">Share your <span>awesomeness</span></div>

            <a href="//twitter.com/home?status=Lets%20all%20donate%20%23KitStart%20%23DonateToday" onclick="window.open(this.href, 'mywin',
            'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;"><img src="http://res.cloudinary.com/dxhabwozn/image/upload/v1430876274/TwitterBadge-250px_nwapiz.png"></a>
            <a href="https://www.facebook.com/sharer/sharer.php?u=http://whispering-peak-5480.herokuapp.com" onclick="window.open(this.href, 'mywin',
            'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;">
            <img src="http://res.cloudinary.com/dxhabwozn/image/upload/v1430876269/Facebookbadge-250px_zzcbz9.png">
          </a>

          <div class="heading-box">Tell your <span>Friends</span> to be awesome</div>


          <form class="bs-example bs-example-form" data-example-id="simple-input-groups">
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Email</span>
              <input type="text" class="form-control" placeholder="" aria-describedby="basic-addon1">
            </div>
            <br>
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Email</span>
              <input type="text" class="form-control" placeholder="" aria-describedby="basic-addon1">
            </div>
            <br>
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Email</span>
              <input type="text" class="form-control" placeholder="" aria-describedby="basic-addon1">
            </div>
            <br>
          </form>

          <a href="success"><div class="donatetodayblack">Email <span>them</span></div></a>


        </div>
      </div>

    </div>

app/views/homepage/team.html.erb
      <div class="row">
        <div class="topsection set-height ourteam description">

            <!-- <div class="col-md-12 ourteam" style=""> -->

              <div class="shadow">

                <p class="ourteamtitle">James&nbsp;&nbsp;|&nbsp;&nbsp;Joe&nbsp;&nbsp;|&nbsp;&nbsp;Julian</p>
                
                <p>Brought together by Night Shift. Inspired by Charlotte. Fueled by Pizza & Beer.</p>
              </div>              
            <!-- </div> -->


<!-- <p class="ourteamtitle">James&nbsp;&nbsp;|&nbsp;&nbsp;Joe&nbsp;&nbsp;|&nbsp;&nbsp;Julian</p> -->
                


        </div>
        
          <div class="row" style="text-align: center;">
            <div class="col-md-offset-3 col-sm-6">
              <h3>Other<br>Contributors</h3>
            </div>
          </div><!-- /.row -->
          <div class="row" style="text-align: center;">
           <div class="col-md-offset-3 col-sm-2">
             <img class="img-square" src="http://placehold.it/140x140/008F89&text=SBA" alt="Generic placeholder image" width="140" height="140">
             <h2>Simone</h2>
             <p>Developer</p>
           </div><!-- /.col-sm-4 -->        
           <div class="col-sm-2">
              <img class="img-square" src="http://placehold.it/140x140/008F89&text=HL" alt="Generic placeholder image" width="140" height="140">
             <h2>Hannah</h2>
             <p>Adjunct</p>

           </div><!-- /.col-sm-4 -->
           <div class="col-sm-2">
             <img class="img-square" src="http://placehold.it/140x140/008F89&text=RH" alt="Generic placeholder image" width="140" height="140">
             <h2>Rebecca</h2>
             <p>Designer</p>
           </div><!-- /.col-sm-4 -- >
          </div>
      </div>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kit_id %><br>
    <%= f.number_field :kit_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Kit</th>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.kit_id %></td>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kit:</strong>
  <%= @item.kit_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/kits/_form.html.erb
<%= form_for(@kit) do |f| %>
  <% if @kit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kit.errors.count, "error") %> prohibited this kit from being saved:</h2>

      <ul>
      <% @kit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.number_field :organization_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.number_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kits/edit.html.erb
<h1>Editing kit</h1>

<%= render 'form' %>

<%= link_to 'Show', @kit %> |
<%= link_to 'Back', kits_path %>

app/views/kits/index.html.erb
<h1>Listing kits</h1>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Name</th>
      <th>Description</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kits.each do |kit| %>
      <tr>
        <td><%= kit.organization_id %></td>
        <td><%= kit.name %></td>
        <td><%= kit.description %></td>
        <td><%= kit.total %></td>
        <td><%= link_to 'Show', kit %></td>
        <td><%= link_to 'Edit', edit_kit_path(kit) %></td>
        <td><%= link_to 'Destroy', kit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kit', new_kit_path %>

app/views/kits/new.html.erb
<h1>New kit</h1>

<%= render 'form' %>

<%= link_to 'Back', kits_path %>

app/views/kits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization:</strong>
  <%= @kit.organization_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @kit.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @kit.description %>
</p>

<p>
  <strong>Total:</strong>
  <%= @kit.total %>
</p>

<%= link_to 'Edit', edit_kit_path(@kit) %> |
<%= link_to 'Back', kits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Kit Start | <%= @org.name %></title>
<!-- this css and junk is really confusing me and my style :)
  <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag 'bootstrap.min' %>
  <%= stylesheet_link_tag 'navbar' %>
  <%= javascript_include_tag 'application' %>
  
  <%= csrf_meta_tags %>
-->
  <%= favicon_link_tag 'favicon.png' %>
  <!-- Bootstrap core CSS -->
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  
  <!-- custom CSS -->
  <%= stylesheet_link_tag 'custom' %>

  <!-- makes nav bar clickable -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/js/bootstrap.js"></script>
</head>
<body>
      <%= render template: 'layouts/nav' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
      <%= render template: 'layouts/footer' %>
</body>
</html>

app/views/layouts/footer.html.erb
<footer class="footer">
  <p>&copy; <%= DateTime.now.strftime('%Y') %> KIT START, ALL RIGHTS RESERVED</p>
</footer>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :lft %><br>
    <%= f.number_field :lft %>
  </div>
  <div class="field">
    <%= f.label :rgt %><br>
    <%= f.number_field :rgt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th>Lft</th>
      <th>Rgt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.parent_id %></td>
        <td><%= organization.lft %></td>
        <td><%= organization.rgt %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @organization.parent_id %>
</p>

<p>
  <strong>Lft:</strong>
  <%= @organization.lft %>
</p>

<p>
  <strong>Rgt:</strong>
  <%= @organization.rgt %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>